#! /bin/bash

inp_name=$1

antipathy="/mnt/c/Program Files (x86)/Druide/Antidote 10/Application/Bin64/Antidote.exe"
lin_help_path="/mnt/c/SVN/Echoview13/Documentation/Help_file/contents"
antitemppathy="/mnt/c/Users/vasaantk/AppData/Local/Temp/antitmp"

if [[ -z "$inp_name" ]]; then
    echo '# Accepts a file name and searches the current dir for the file. If it'
    echo '# finds the file, it runs Antidote on the file.'
    echo '#'
    echo '# Usage:'
    echo '#     -->$ auto-anti input.txt'
else
    cd "$lin_help_path"
    find_file=$(find . -type f -name "$inp_name")

    if [[ -f "$antitemppathy" ]]; then
        rm "$antitemppathy"
    fi

    lynx --dump "$find_file" | tr -s ' '  >> "$antitemppathy"
    # links -dump "$find_file" | tr -s ' ' >> "$antitemppathy"
    # pandoc -s -f html "$find_file" -t plain -o "$antitemppathy"

    winpath=$(wslpath -w "$antitemppathy")
    "$antipathy" "$winpath"
fi
