#! /bin/bash

usrhtm=$@
htm_path=/mnt/c/SVN/Echoview13/Documentation/Help_file/contents

if [[ -z "$usrhtm" ]] ; then
    echo "# find-qa-tags takes the file name from the command line and searches"
    echo "# in ""$htm_path"
    echo "# for QA tags in the file."
    echo "#"
    echo "# Usage"
    echo "#    -->$ find-qa-tags \*.htm"
    echo "#    -->$ find-qa-tags \*properties\*.htm"
    echo "#    -->$ find-qa-tags  Echogram_keyboard_shortcuts.htm"
fi

main(){

    local foundfile_main=$1
    local stopstring_main="<h1"
    local grepstring_main="data-condition=\"Others"

    checkfortag "$stopstring_main" "$foundfile_main"

    if [[ $? -eq 0 ]] ; then
        tailme_main=$(catfromline "$foundfile_main" "$stopStringLine")
        findqatags "$tailme_main" "$grepstring_main" "$foundfile_main"
    else
        echo "$stopstring_main" " not in " "$foundfile_main"
    fi
}

checkfortag(){
    local stopstring_cft=$1
    local foundfile_cft=$2
    stopStringLine=$(grep -n -m 1 "$stopstring_cft" "$foundfile_cft")
}

catfromline(){
    local catfile=$1
    local catFromLineString=$2
    filelen=$(cat "$catfile" | wc -l)
    catfromline_cfl=$(echo "$catFromLineString" | cut -f 1 -d :)
    tailme_cfl=$(echo "$filelen" - "$catfromline_cfl" + 1 | bc)
    echo "$tailme_cfl"
}

findqatags(){
    local tailme_fqt=$1
    local grepstring_fqt=$2
    local findqatagFile=$3
    foundqatags=$(tail -n "$tailme_fqt" "$findqatagFile" | grep -no "$grepstring_fqt")
    if [[ $? -eq 0 ]] ; then
        echo "$findqatagFile"
        echo "$foundqatags"
        echo ""
    fi
}

export -f main
export -f checkfortag
export -f catfromline
export -f findqatags

find "$htm_path" -type f -name "$usrhtm" -exec bash -c 'main "$0"' {} \;
