#! /bin/bash

# In theory, this ought to be a very nice script to automaticallly
# copy the latest Echoview build from '\\fserve\echoview_private\' to
# the local dir. However, the copying process is very slow.

# sudo mkdir /mnt/p
# sudo mount -t drvfs '\\fserve\echoview_private' /mnt/p

# echo_new=$(ls -td /mnt/p/Version\ 13.1/Builds/* | head -1)
echo_new=$(ls -td /mnt/p/Version\ 14.0/Builds/* | head -1)
echo_ver=$(basename "$echo_new")
dest_dir=/mnt/c/Echoview\ 14/
if [[ ! -d "$dest_dir$echo_ver" ]]; then
    cp -rf "$echo_new" "$dest_dir"
    getdeps="$dest_dir$echo_ver"/WIN64_RELEASE/_GetRunTimeDependencies.bat
    explorer.exe "$(wslpath -w "$getdeps")"
    echo "$dest_dir""$echo_ver"
else
    echo "$echo_new" "is the latest version."
fi
