#! /bin/bash

# Automatically open the latest .chm on my system found by open-echo.

source open-echo
chm_executable_subdir="WIN64_RELEASE"


main(){
    local ev_files_dir=$1
    local ev_dir_prefix=$2
    local release_subdir=$3

    latest_ev_version_index=$(get_latest_ev_version "$ev_files_dir" "$ev_dir_prefix")
    open_latest_chm "$ev_files_dir" "$ev_dir_prefix" "$latest_ev_version_index" "$release_subdir"
}


open_latest_chm(){
    local root_dir=$1
    local ev_dir_prefix=$2
    local latest_version=$3
    local release_subdir=$4

    cd "$root_dir"/"$ev_dir_prefix"."$latest_version"*/"$release_subdir"
    newest_chm_found=$(ls -t *.chm | head -1)
    echo "Opening" "$newest_chm_found"
    explorer.exe "$newest_chm_found"
}


execute_chm(){
    local root_dir=$1
    local ev_dir_prefix=$2
    local latest_version=$3
    local exe_location=$4
    "$root_dir"/"$ev_dir_prefix"."$latest_version"*/"$exe_location" & disown
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$echoview_files_dir" "$echoview_dir_prefix" "$chm_executable_subdir"
fi
