#! /bin/bash

# A kludge to automatically open the latest version of Echoview on my
# system.

echoVer=-1
cd /mnt/c/Echoview\ 13/
for item in .
do
    if [ -d "$item" ]; then
        for ver in $(ls $item | cut -f 2 -d ' ' | cut -f 3 -d '.')
        do
            if [ "$ver" -gt "$echoVer" ]; then
                echoVer="$ver"
            fi
        done
    fi
done

# Check if the help file exists
cd /mnt/c/Echoview\ 13/Echoview\ 13.0.$echoVer*/WIN64_RELEASE/

if [[ -z "$(ls Echoview_*.chm)" ]]; then
    echo "Help file does not exist"
else
    explorer.exe "$(ls Echoview_*.chm)"
fi
