#! /bin/bash

# A kludge to automatically open the latest version of Echoview 12 on
# my system.

echoVer=-1
cd /mnt/c/Echoview\ 12/
for item in .
do
    if [ -d "$item" ]; then
        for ver in $(ls $item | cut -f 2 -d ' ' | cut -f 3 -d '.')
        do
            if [ "$ver" -gt "$echoVer" ]; then
                echoVer="$ver"
            fi
        done
    fi
done

# Check if the help file exists
cd /mnt/c/Echoview\ 12/Echoview\ 12.0.$echoVer*/WIN64_RELEASE/
if [ ! -f "Echoview.chm" ]; then
    cp /mnt/c/SVN/Echoview12/Documentation/Help_file/\!SSL\!/Echoview_help_file_layouts/Echoview.chm .
fi

# Execute the program
Echoview.exe & disown
