#! bin/bash

source open-echo

help_file_page=$1
chm_file_path=$2
help_file_project_path="/mnt/c/SVN/Echoview13/Documentation/Help_file/contents"


if [[ -z "$help_file_page" ]]; then

    echo "# open-help-page obtains the relative path to the user-specified"
    echo "# page in" $help_file_project_path
    echo "# It then opens that page in the .chm provided by the user."
    echo "#"
    echo "# Example usage:"
    echo "#"
    echo "#    -->$ open-help-page Using_CTD_data.htm"
    echo "#    -->$ open-help-page About_single_targets.htm#Target_lengths Echoview\ 2032/Echoview.chm"
    exit
fi


main(){

    local help_file_page=$1
    local help_file_project_path=$2
    local chm_file_path=$3

    if [[ -z "$chm_file_path" ]]; then
        latest_ev_version_index=$(get_latest_ev_version "$echoview_files_dir" "$echoview_dir_prefix")
        chm_file_path="$(ls -t "$echoview_files_dir"/"$echoview_dir_prefix"."$latest_ev_version_index"*/"$echoview_executable_subdir"/*.chm | head -1)"
    fi

    has_relative_link=$(check_relative_link "$help_file_page")

    if [[ "$has_relative_link" == "true" ]]; then
        {
            find_file=$(grab_filename_only "$help_file_page")
        }
    else
        find_file="$help_file_page"
    fi

    # # TODO: Incorporate a choosing function for when there are
    # # multiple hits from find.
    found_file=$(find "$help_file_project_path" -type f -name "$find_file")
    dir_of_page=$(dirname "$found_file")
    relative_dirpath=$(relative_chm_path "$help_file_project_path" "$dir_of_page")
    open_page=$(echo "$relative_dirpath"/"$help_file_page")
    open_help_page "$chm_file_path" "$open_page"
}


check_relative_link(){
    local userinput=$1
    if [[ "$userinput" == *#* ]]; then
        echo "true"
    else
        echo "false"
    fi
}


grab_filename_only(){
    local userinput=$1
    local delim="#"
    echo "$userinput" | cut -d "$delim" -f 1
}


relative_chm_path(){
    local projectpath=$1
    local pagedir=$2
    local IFS="/"
    read -ra subdirs <<< "$projectpath"
    cutpathcount=$(echo "${#subdirs[@]} + 1" | bc)
    echo "$pagedir" | cut -d "$IFS" -f "$cutpathcount"-
}


open_help_page(){
    local chmpath=$1
    local pagepath=$2
    cd "$(dirname "$chmpath")"
    HH.EXE "$(basename "$chmpath")"::"$pagepath" & disown
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$help_file_page" "$help_file_project_path" "$chm_file_path"
fi
