#! /bin/bash

# Automatically open the latest .chm on my system found by open-echo.

source open-echo
chm_executable_subdir="WIN64_RELEASE"


main(){
    local ev_files_dir=$1
    local ev_dir_prefix=$2
    local release_subdir=$3

    latest_ev_version_index=$(get_latest_ev_version "$ev_files_dir" "$ev_dir_prefix")
    chm_path_name="$(get_latest_chm "$ev_files_dir" "$ev_dir_prefix" "$latest_ev_version_index" "$release_subdir")"
    open_chm "$chm_path_name"
}


get_latest_chm(){
    local root_dir=$1
    local ev_dir_prefix=$2
    local latest_version=$3
    local release_subdir=$4

    cd "$root_dir"/"$ev_dir_prefix"."$latest_version"*/"$release_subdir"
    newest_chm_found=$(ls -t *.chm | head -1)
    echo "$(pwd)"/"$newest_chm_found"
}


open_chm(){
    local chm_path_name=$1
    cd "$(dirname "$chm_path_name")"
    chm_file="$(basename "$chm_path_name")"
    echo "Opening" "$chm_file"
    explorer.exe "$chm_file" & disown
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$echoview_files_dir" "$echoview_dir_prefix" "$chm_executable_subdir"
fi
