#! /bin/bash

ormod=$1
jira=$2
cd /mnt/c/Users/VasaantK/OneDrive\ -\ Echoview\ Software/Evernote/Jirae

if [[ -z "$ormod" ]] && [[ -z "$jira" ]]; then
    echo "# ormod changes the mode (like chmod) of org file in the defined"
    echo "# file. Valid modes are:"
    echo "# "
    echo "# u :  No mode"
    echo "# td:  TODO"
    echo "# ip:  IN-PROGRESS"
    echo "# wa:  WAITING"
    echo "# d :  DONE"
    echo "# "
    echo "# Usage:"
    echo "#     -->$ ormod td 28889"
    exit
fi

if ! [[ -f \#$2.org ]]; then
    echo No ticket
    exit
fi

vanilla="* #$jira"
todo="* TODO #$jira"
inprog="* IN-PROGRESS #$jira"
wait="* WAITING #$jira"
done="* DONE #$jira"

if ! [[ -z $(grep "$vanilla" -m 1 \#$2.org) ]] ; then
    currMod="$vanilla"
fi
if ! [[ -z $(grep "$todo" -m 1 \#$2.org) ]] ; then
    currMod="$todo"
fi
if ! [[ -z $(grep "$inprog" -m 1 \#$2.org) ]] ; then
    currMod="$inprog"
fi
if ! [[ -z $(grep "$wait" -m 1 \#$2.org) ]] ; then
    currMod="$wait"
fi
if ! [[ -z $(grep "$done" -m 1 \#$2.org) ]] ; then
    currMod="$done"
fi

if [[ -z "$currMod" ]]; then
    echo "No mode found in" \#$2.org
    exit
fi
echo Change: "$currMod"

u=" "
td="TODO"
ip="IN-PROGRESS"
wa="WAITING"
d="DONE"

if [[ $ormod == "u" ]]; then
    newmod="$vanilla"
fi
if [[ $ormod == "td" ]]; then
    newmod="$todo"
fi
if [[ $ormod == "ip" ]]; then
    newmod="$inprog"
fi
if [[ $ormod == "wa" ]]; then
    newmod="$wait"
fi
if [[ $ormod == "d" ]]; then
    newmod="$done"
fi

if [[ -z "$newmod" ]]; then
    echo "Invalid change mode requested. Use:"
    echo "u td ip wa d"
    exit
fi
echo "    to:" "$newmod"


read -p "Change mode? y/[n]: " usrinp
if [[ -z "$usrinp" ]]; then
    exit
fi
if [[ "$usrinp" == "y" ]]; then
    sed -i "s|$currMod|$newmod|" \#$2.org
    echo "Mode changed."
fi
