#! /bin/bash

USR_DIR=$1

if [[ -z "$USR_DIR" ]]; then
    echo '# Accepts either a dir or a single file as an argument. For each html'
    echo '# file (in the dir), it searches for double-words (e.g. " mop mop ").'
    echo '#'
    echo '# Usage:'
    echo '#     -->$ repeat-chars usr_dir'
    echo '#     -->$ repeat-chars usr_file'
    exit
fi

findrep(){
    local funcarg=$1
    local second=false

    # Remove HTML tags using sed and loop through each word
    for word in $(cat "$funcarg" | sed 's/<[^>]*>//g')
    do
        first="$word"
        # If there is more than one char (because blanklines count as
        # a char, apparently) and the text are alphabets only
        if (( ${#first} > 1 )) && [[ "$first" =~ ^[A-Za-z]+$ ]]; then
            if [[ "$first" == "$second" ]]; then
                echo "$funcarg" '===>' "$first" "$second"
            fi
        fi
        second="$first"
    done
}

if [[ -d "$USR_DIR" ]]; then
    for INP_FILE in $(find "$USR_DIR" -type f -name "*.htm")
    do
        findrep $INP_FILE
    done
else
    find_file=$(find . -type f -name "$USR_DIR")
    findrep "$find_file"
fi
